# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e08c007eed5f7a3602388f3ec7f10a41617e393f17007e66f6b4bbf816876f0589ec66b8bdc4c4d302dbf3e7a1cdebe4ddc2871bf6899db492a06d1f2a0d1659

test:
  secret_key_base: 5ca4e1d6f25563d946c2a5413e7dd37703b354e36158d5aa940b5dc40f9f24b2315f7faaca770faa3a94c054f7c45fe431c543288c6cb6da0bb79d5b8ac9bf7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
